# Generated by Django 5.0.2 on 2024-03-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2000-09-22'),
            preserve_default=False,
        ),
    ]
